openapi: 3.0.1
info:
  title: Foodo API
  description: API documentation for Foodo
  version: 1.0.0
  contact:
    email: romadhonatatang@gmail.com
servers:
  - url: http://localhost:3000/api
    description: Development server
